# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema.status]
file = "src/schema/status.rs"
with_docs = true
filter = { only_tables = ["status"] }
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/home/thimotee/work/rust_work/todo/migrations"
